### ISSUE TITLE
Errror Running Gradle task 'assembleDebug'

### ISSUE THREAD

**Issue by jordantsap** [roketstorm/smsker#1]
Launching lib\main.dart on M2003J15SC in debug mode...
Running Gradle task 'assembleDebug'...
e: C:\Users\jordan\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\smsker-0.0.1\android\src\main\kotlin\com\roketstorm\smsker\SmskerPlugin.kt: (48, 34): Unresolved reference: arguments
e: C:\Users\jordan\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\smsker-0.0.1\android\src\main\kotlin\com\roketstorm\smsker\SmskerPlugin.kt: (48, 58): Unresolved reference: arguments

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':smsker:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by roketstorm** [comment]
Fixed in version 0.1.1

**Comment by jordantsap** [comment]
What is the latest version??

**Comment by roketstorm** [comment]
> What is the latest version??

Check out https://pub.dev/packages/smsker
