### ISSUE TITLE
Android related permission error but uses-permission is in manifest

### ISSUE THREAD

**Issue by jordantsap** [roketstorm/smsker#2]
The manifest file is:
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example.feelsafe_dev">
    <uses-permission android:name="android.permission.SEND_SMS"/>
   <application

but i get ...

Running Gradle task 'assembleDebug'...
E/flutter (17922): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, Sending SMS message: uid 10153 does not have android.permission.SEND_SMS., null, java.lang.SecurityException: Sending SMS message: uid 10153 does not have android.permission.SEND_SMS.
E/flutter (17922): 	at android.os.Parcel.readException(Parcel.java:1620)
E/flutter (17922): 	at android.os.Parcel.readException(Parcel.java:1573)
E/flutter (17922): 	at com.android.internal.telephony.ISms$Stub$Proxy.sendTextForSubscriber(ISms.java:1577)
E/flutter (17922): 	at android.telephony.SmsManager.sendTextMessageInternal(SmsManager.java:380)
E/flutter (17922): 	at android.telephony.SmsManager.sendTextMessage(SmsManager.java:333)
E/flutter (17922): 	at com.roketstorm.smsker.SmskerPlugin.onMethodCall(SmskerPlugin.kt:48)
E/flutter (17922): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (17922): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (17922): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:738)
E/flutter (17922): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (17922): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/flutter (17922): 	at android.os.Looper.loop(Looper.java:143)
E/flutter (17922): 	at android.app.ActivityThread.main(ActivityThread.java:7231)
E/flutter (17922): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (17922): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/flutter (17922): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
E/flutter (17922): )
E/flutter (17922): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter (17922): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:162:18)
E/flutter (17922): <asynchronous suspension>
E/flutter (17922): #2      Smsker.sendSms (package:smsker/smsker.dart:16:30)
E/flutter (17922): <asynchronous suspension>
E/flutter (17922): #3      _MyAppState._sendMessage (package:feelsafe_dev/main.dart:20:5)
E/flutter (17922): <asynchronous suspension>
E/flutter (17922): 
E/flutter (17922): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, Sending SMS message: uid 10153 does not have android.permission.SEND_SMS., null, java.lang.SecurityException: Sending SMS message: uid 10153 does not have android.permission.SEND_SMS.
E/flutter (17922): 	at android.os.Parcel.readException(Parcel.java:1620)
E/flutter (17922): 	at android.os.Parcel.readException(Parcel.java:1573)
E/flutter (17922): 	at com.android.internal.telephony.ISms$Stub$Proxy.sendTextForSubscriber(ISms.java:1577)
E/flutter (17922): 	at android.telephony.SmsManager.sendTextMessageInternal(SmsManager.java:380)
E/flutter (17922): 	at android.telephony.SmsManager.sendTextMessage(SmsManager.java:333)
E/flutter (17922): 	at com.roketstorm.smsker.SmskerPlugin.onMethodCall(SmskerPlugin.kt:48)
E/flutter (17922): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (17922): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (17922): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:738)
E/flutter (17922): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (17922): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/flutter (17922): 	at android.os.Looper.loop(Looper.java:143)
E/flutter (17922): 	at android.app.ActivityThread.main(ActivityThread.java:7231)
E/flutter (17922): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (17922): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/flutter (17922): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
E/flutter (17922): )
E/flutter (17922): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter (17922): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:162:18)
E/flutter (17922): <asynchronous suspension>
E/flutter (17922): #2      Smsker.sendSms (package:smsker/smsker.dart:16:30)
E/flutter (17922): <asynchronous suspension>
E/flutter (17922): #3      _MyAppState._sendMessage (package:feelsafe_dev/main.dart:20:5)
E/flutter (17922): <asynchronous suspension>
E/flutter (17922): 
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Error connecting to the service protocol: failed to connect to http://127.0.0.1:62636/EZmL0jhuojc=/

**Comment by roketstorm** [comment]
Can you provide your manifest file please?
Or try to insert permission tag `<uses-permission android:name="android.permission.SEND_SMS" />` on the `<manifest>` level

**Comment by jordantsap** [comment]
At first i had the user-permission tag above application tag and it did not work, after i putted it below </application> it worked. But shouldn't i put it above??

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.feelsafetest">

   <application
        android:label="feelsafetest"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
    <uses-permission android:name="android.permission.SEND_SMS" />
    <uses-permission android:name="android.permission.INTERNET" />

</manifest>`

**Comment by roketstorm** [comment]
This is just some metadata, it should ignore order of tags. Glad, it works!

**Comment by jordantsap** [comment]
Same again

**Comment by jordantsap** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example.feelsafe">

    <uses-permission android:name="android.permission.SEND_SMS" />
    <uses-permission android:name="android.permission.INTERNET" />

    
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="feelsafe"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>

</manifest>

**Comment by roketstorm** [comment]
Try to play with `minSdkVersion` or `targetSdkVersion`. One of them should be below 23.
It seems than this permission become `dangerous` since 23 version of SDK, so besides `manifest` you should check permission in runtime.

I'll try to fix this in future releases.

**Comment by jordantsap** [comment]
Yes i found this wordaround as well,
Should i download sdk 22 in android studio settings as well?

**Comment by jordantsap** [comment]
Somewhere says that you should ask for permission at runtime

**Comment by jordantsap** [comment]
I managed to make it work using another package, https://pub.dev/packages/permission_handler.
Are you going to emplement the function with dart, or maybe i can create a pull request?
What is your opinion??

**Comment by roketstorm** [comment]
I'll implement it in the next version. Thanks!
